//import "jquery.min"
//import "jquery/dist/jquery"
//import "bootstrap.bundle.min"
//import "jquery.easing.min"
//import "sb-admin-2.min"
//import "bootstrap-growl-ifightcrime/jquery.bootstrap-growl"
import "@nathanvda/cocoon"
